apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadrivers-demo
  namespace: datadrivers-demo
  labels:
    app: datadrivers-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: datadrivers-demo
  template:
    metadata:
      labels:
        app: datadrivers-demo
    spec:
      containers:
      - image: 600627322473.dkr.ecr.eu-west-3.amazonaws.com/datadrivers-demo_docker_image:stable
        imagePullPolicy: Always
        name: datadriver-demo
        env:
          KUBERNETES_CONFIG_MOUNT_PATH: /config
        volumeMounts:
          - name: config-volume
              mountPath: /config
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 15
      volumes:
        - name: config-volume
          configMap:
            name: datadriver-demo-helloworld-config
