apiVersion: v1
kind: Service
metadata:
  name: datadrivers-demo
  namespace: datadrivers-demo
  labels:
    app: datadrivers-demo
spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: datadrivers-demo
  sessionAffinity: None
  type: ClusterIP
