apiVersion: v1
kind: Service
metadata:
  namespace: datadrivers-demo
  name: datadrivers-demo-lb
spec:
  selector:
    app: datadrivers-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

