---
name: "Deploy"
on: [push]

jobs:
  Run:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.G_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Run CI Script
        run: |
          if [ -n "$STAGE" ]
          then
            nix develop --command ci-local -s $STAGE -d
          else
            nix develop --command ci-local -s ${{ github.head_ref || github.ref_name }}
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: ${{ github.ref == 'refs/heads/releases/prod' && 'prod' || github.ref == 'refs/heads/releases/dev' && 'dev' || '' }}
