name: "Test"
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Terraform state
        uses: devgioele/terraform-state-artifact@v4
        with:
          passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
          download_upload: download
        continue-on-error: true

      - uses: cachix/install-nix-action@v18
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#
          interpreter: bash
          clearEnvForScript: false
          script: |
            # use strict
            set -e
            set -u
            set -o pipefail

            env
            cd terraform
            terraform init
            terraform validate
